/*
 * Generated by MTK SP DrvGen Version 10.03.0 for MT6589_NP. Copyright MediaTek Inc. (C) 2012.
 * Wed Feb 26 10:19:52 2014
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


